# Generated by Django 4.2.7 on 2023-12-06 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import productos.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0003_fabricante_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(default=productos.models.Categoria.get_default_categoria, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='productos', to='productos.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fabricante',
            field=models.ForeignKey(default=productos.models.Fabricante.get_default_fabricante, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='productos', to='productos.fabricante'),
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuerpo', models.CharField(max_length=500)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='productos.producto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
