# Generated by Django 4.2.7 on 2023-12-06 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_producto_categoria_alter_producto_fabricante_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opinion',
            options={'ordering': ['producto'], 'verbose_name_plural': 'Opiniones'},
        ),
    ]
