# Generated by Django 4.2.7 on 2023-12-06 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_opinion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
    ]
