# Generated by Django 4.2.7 on 2023-12-11 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_alter_opinion_producto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fabricante',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Todos los fabricantes'},
        ),
    ]
