# Generated by Django 4.2.7 on 2023-12-11 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_alter_fabricante_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fabricante',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Fabricantes'},
        ),
    ]
