# Generated by Django 4.2.7 on 2023-12-11 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_categoria_icono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opinion',
            old_name='cuerpo',
            new_name='tu_opinion',
        ),
    ]
