# Generated by Django 4.2.7 on 2023-12-11 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_rename_cuerpo_opinion_tu_opinion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='icono',
        ),
    ]
