# Generated by Django 4.2.7 on 2023-11-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_email_cliente_nombre_alter_cliente_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(blank=True, default='Nombre Completo', max_length=254, null=True),
        ),
    ]
