# Generated by Django 4.2.7 on 2023-11-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='apellido1',
            field=models.CharField(blank=True, default='Primer apellido', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellido2',
            field=models.CharField(blank=True, default='Segundo apellido', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(blank=True, default='Nombre', max_length=254, null=True),
        ),
    ]
