# Generated by Django 4.2.7 on 2023-11-29 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_remove_cliente_direccion'),
        ('clientes', '0006_alter_cliente_apellidos_alter_cliente_direccion_and_more'),
    ]

    operations = [
    ]
