# Generated by Django 4.2.7 on 2023-11-29 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_cliente_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='direccion',
        ),
    ]
