# Generated by Django 4.2.7 on 2023-11-29 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_remove_direccionenvio_cliente_remove_pedido_cliente_and_more'),
        ('clientes', '0009_remove_cliente_direccion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
