# Generated by Django 4.2.7 on 2023-12-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccioncliente',
            name='formaPago',
            field=models.CharField(choices=[('contrarrempolso', 'Contrareenbolso'), ('pasarela', 'Tarjeta de crédito')], default='contrarrempolso', max_length=50),
        ),
    ]
