# Generated by Django 4.2.7 on 2023-12-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_remove_direccionenvio_cliente_remove_pedido_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(blank=True, choices=[('En preparación', 'En preparación'), ('Enviado', 'Enviado'), ('Entregado', 'Entregado')], max_length=20, null=True),
        ),
    ]
