# Generated by Django 4.2.7 on 2023-12-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='productopedido',
            name='montar_domicilio',
            field=models.BooleanField(default=False),
        ),
    ]
