# Generated by Django 4.2.7 on 2023-12-07 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_reclamacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamacion',
            name='user',
        ),
    ]
