# Generated by Django 4.2.7 on 2023-12-10 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_reclamacion_resolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamacion',
            name='resolucion',
            field=models.CharField(choices=[('por_resolver', 'Por Resolver'), ('en_proceso', 'En Proceso'), ('solucionado', 'Solucionado')], default='por_resolver', max_length=20, verbose_name='Estado de la Reclamación'),
        ),
    ]
