# Generated by Django 4.2.7 on 2023-12-10 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_productopedido_montar_domicilio'),
        ('pedidos', '0007_alter_reclamacion_resolucion'),
    ]

    operations = [
    ]
