# Generated by Django 4.2.7 on 2023-12-11 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_merge_20231210_1928'),
        ('pedidos', '0008_merge_20231211_0851'),
    ]

    operations = [
    ]
