# Generated by Django 4.2.7 on 2023-12-11 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_merge_20231211_0911'),
        ('pedidos', '0009_merge_20231211_1039'),
    ]

    operations = [
    ]
