# Generated by Django 4.2.7 on 2023-12-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_merge_20231211_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='destinatario',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
