# Generated by Django 4.2.7 on 2023-12-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_pedido_destinatario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='destinatario',
            field=models.CharField(max_length=1000),
        ),
    ]
